%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                             %
%   Center for Astronomy Signal Processing and Electronics Research           %
%   http://seti.ssl.berkeley.edu/casper/                                      %
%   Copyright (C) 2007 Terry Filiba, Aaron Parsons                            %
%                                                                             %
%   This program is free software; you can redistribute it and/or modify      %
%   it under the terms of the GNU General Public License as published by      %
%   the Free Software Foundation; either version 2 of the License, or         %
%   (at your option) any later version.                                       %
%                                                                             %
%   This program is distributed in the hope that it will be useful,           %
%   but WITHOUT ANY WARRANTY; without even the implied warranty of            %
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             %
%   GNU General Public License for more details.                              %
%                                                                             %
%   You should have received a copy of the GNU General Public License along   %
%   with this program; if not, write to the Free Software Foundation, Inc.,   %
%   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.               %
%                                                                             %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function ramdata_arrange_wrctrl_init(blk, varargin)
clog('entering ramdata_arrange_wrctrl_init','trace');
% Declare any default values for arguments you might like.
defaults = {'Data_width', 5, 'Total_channnel', 2, ...
    'bram_latency', 2};

if same_state(blk, 'defaults', defaults, varargin{:}), return, end
clog('uwl_packet_init post same_state','trace');
check_mask_type(blk, 'ramdata_arrange_wrctrl');
munge_block(blk, varargin{:});



Data_width = get_var('Data_width', 'defaults', defaults, varargin{:});
Total_channnel = get_var('Total_channnel', 'defaults', defaults, varargin{:});
shift_num = lcm(Data_width, 512)/Data_width;


delete_lines(blk);

reuse_block(blk, 'sys_rst', 'built-in/inport', ...
    'Position', [0 0 30 0+15], 'Port', num2str(1));

reuse_block(blk, 'data_valid', 'built-in/inport', ...
    'Position', [0 50 30 50+15], 'Port', num2str(2));

reuse_block(blk, 'data_in', 'built-in/inport', ...
    'Position', [0 100 30 100+15], 'Port', num2str(3));


% creat input cnt 
x = 1000;y= 0;x_width = 100;y_width = 100;
reuse_block(blk, 'in_data_carry_cnt', 'uwl_lib/carry_cnt', ...
    'Position', [x y x+x_width y+y_width],...
    'cnt_width', '8',...
    'cnt_limit'  , num2str(shift_num-1),...
    'cnt_init_value'  , '0',...
    'cnt_init_step'  , '1'...    
    );
x = 1000;y= 200;x_width = 100;y_width = 100;
reuse_block(blk, 'in_shift_data_valid', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width],...
    'en', 'off'... 
    );

add_line(blk, 'sys_rst/1', 'in_data_carry_cnt/1');
add_line(blk, 'data_valid/1', 'in_data_carry_cnt/2');
add_line(blk, 'in_data_carry_cnt/2', 'in_shift_data_valid/1');
% creat input shift 
x = 1000;y= 900-25;x_width = 100;y_width = 100;
last_name = '';
for i=1:shift_num
    name = ['in_data_shift' num2str(i-1)];
    reuse_block(blk, name, 'xbsIndex_r4/Register', ...
        'Position', [x y x+x_width y+y_width],...
        'en', 'on'... 
        );
    
    if i == 1
        add_line(blk, 'data_in/1', [name '/1']);  
    else
        add_line(blk, [last_name '/1'], [name '/1']);
    end
    
    add_line(blk, 'data_valid/1', [name '/2']);
    last_name = name;
    y = y + 100;    
end

% creat output shift 
x = 2000;y= 900;x_width = 100;y_width = 100;
for i=1:shift_num
    name = ['data_shift_out' num2str(i-1)];
    reuse_block(blk, name, 'uwl_lib/shift_out', ...
        'Position', [x y x+x_width y+y_width],...
        'Datain_width', '320',...         
        'shiftout_width', '32'... 
        );
    
    front_blk_name = ['in_data_shift' num2str(i-1)];
    add_line(blk, [front_blk_name '/1'], [name '/1']);
    add_line(blk, 'in_shift_data_valid/1', [name '/2']);
    y = y + 100;    
end

% creat concat 
x = 3000;y= 900;x_width = 100;y_width = 100*shift_num;
reuse_block(blk, 'data_shift_out_concat', 'xbsIndex_r4/Concat', ...
    'Position', [x y x+x_width y+y_width],...
    'num_inputs', num2str(shift_num)...  
    );


for i=1:shift_num
    name = ['data_shift_out' num2str(i-1)];
    add_line(blk, [name '/1'], ['data_shift_out_concat/' num2str(i)]);
    y = y + 100;    
end

% creat concat_data_carry_cnt 
x = 3000;y= 0;x_width = 100;y_width = 100;
reuse_block(blk, 'concat_data_carry_cnt1', 'uwl_lib/carry_cnt', ...
    'Position', [x y x+x_width y+y_width],...
    'cnt_width', '8',...
    'cnt_limit'  , num2str(Total_channnel-1),...
    'cnt_init_value'  , '0',...
    'cnt_init_step'  , '1'...    
    );
add_line(blk, 'sys_rst/1', 'concat_data_carry_cnt1/1');

x = 3000;y= 200;x_width = 100;y_width = 100;
reuse_block(blk, 'concat_data_carry_cnt2', 'uwl_lib/carry_cnt', ...
    'Position', [x y x+x_width y+y_width],...
    'cnt_width', '8',...
    'cnt_limit'  , '127',...
    'cnt_init_value'  , '0',...
    'cnt_init_step'  , '1'...    
    );
add_line(blk, 'sys_rst/1', 'concat_data_carry_cnt2/1');
add_line(blk, 'concat_data_carry_cnt1/2', 'concat_data_carry_cnt2/2');


% creat pingpang
x = 3000;y= 400;x_width = 100;y_width = 100;
reuse_block(blk, 'pingpang_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width],...
    'rst', 'on',... 
    'en', 'on'...     
    ); 

x = x -200;y_width=100/3;
reuse_block(blk, 'pingpang_Assert', 'xbsIndex_r4/Assert', ...
    'Position', [x y x+x_width y+y_width],...
    'assert_type', 'on',... 
    'type_source', 'Explicitly',...    
    'arith_type', 'Boolean',...        
    'output_port', 'on'...      
    ); 

x = x -200;y_width=100/3;
reuse_block(blk, 'pingpang_not', 'xbsIndex_r4/Inverter', ...
    'Position', [x y x+x_width y+y_width],... 
    'latency', '0'...     
    ); 
add_line(blk, 'pingpang_reg/1', 'pingpang_not/1');
add_line(blk, 'pingpang_not/1', 'pingpang_Assert/1');
add_line(blk, 'pingpang_Assert/1', 'pingpang_reg/1');
add_line(blk, 'sys_rst/1', 'pingpang_reg/2');
add_line(blk, 'concat_data_carry_cnt2/2', 'pingpang_reg/3');

% creat concat validout
x = 3000;y= 600;x_width = 100;y_width = 100;
reuse_block(blk, 'validout_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = x -200;y=600+100/3;y_width = 100/3;
reuse_block(blk, 'valid_pulse', 'casper_library_misc/pulse_ext', ...
    'Position', [x y x+x_width y+y_width],... 
    'pulse_len', num2str(Total_channnel)...     
    ); 


add_line(blk, 'in_shift_data_valid/1', 'valid_pulse/1');
add_line(blk, 'valid_pulse/1', 'validout_reg/1');
add_line(blk, 'validout_reg/1', 'concat_data_carry_cnt1/2');


% creat output
%wr_en output
x = 4000;y= 0;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_en_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 3800;y= 0;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_en_temp_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 5000;y= 50-7.5;x_width = 30;y_width = 15;
reuse_block(blk, 'wr_en', 'built-in/outport', ...
    'Position', [x y x+x_width y+y_width], 'Port', num2str(1));

add_line(blk, 'validout_reg/1', 'wr_en_temp_reg/1');
add_line(blk, 'wr_en_temp_reg/1', 'wr_en_reg/1');
add_line(blk, 'wr_en_reg/1', 'wr_en/1');


%wr_addr output
x = 3599;y= 200;x_width = 100;y_width = 50;
reuse_block(blk, 'Shift', 'xbsIndex_r4/Shift', ...
    'Position', [x y x+x_width y+y_width],...  
    'shift_dir', 'Left',... 
    'shift_bits', '7',...        
    'latency', '0',...  
    'precision', 'User Defined',...  
    'n_bits', num2str(8+7),...      
    'bin_pt', '0'...          
    ); 

x = 4000;y= 400;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_addr_reg', 'xbsIndex_r4/AddSub', ...
    'Position', [x y x+x_width y+y_width],...  
    'precision', 'User Defined',...  
    'n_bits', num2str(ceil(log2(128*2*Total_channnel))),...      
    'bin_pt', '0'...   
    ); 

x = 3800;y= 200;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_addr_temp_reg', 'xbsIndex_r4/AddSub', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 3800;y= 400 + 100*1/4;x_width = 100;y_width = 100;
reuse_block(blk, 'pingpang_Mux', 'xbsIndex_r4/Mux', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 3600;y= 400 + 100*5/8;x_width = 100;y_width = 100/4;
reuse_block(blk, 'constant0', 'xbsIndex_r4/Constant', ...
    'Position', [x y x+x_width y+y_width],...  
    'const', '0',...
    'arith_type', 'Unsigned',...    
    'n_bits', '16',...  
    'bin_pt', '0'...     
    ); 

x = 3600;y= 400 + 100;x_width = 100;y_width = 100/4;
reuse_block(blk, 'constant1', 'xbsIndex_r4/Constant', ...
    'Position', [x y x+x_width y+y_width],...  
    'const', num2str(128*Total_channnel),...
    'arith_type', 'Unsigned',...    
    'n_bits', '16',...  
    'bin_pt', '0'...
    ); 

x = 4000;y= 0;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_en_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 3800;y= 0;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_en_temp_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 5000;y= 450-7.5;x_width = 30;y_width = 15;
reuse_block(blk, 'wr_addr', 'built-in/outport', ...
    'Position', [x y x+x_width y+y_width], 'Port', num2str(1));

add_line(blk, 'concat_data_carry_cnt1/1', 'Shift/1');
add_line(blk, 'Shift/1', 'wr_addr_temp_reg/1');
add_line(blk, 'concat_data_carry_cnt2/1', 'wr_addr_temp_reg/2');

add_line(blk, 'pingpang_reg/1', 'pingpang_Mux/1');
add_line(blk, 'constant0/1', 'pingpang_Mux/2');
add_line(blk, 'constant1/1', 'pingpang_Mux/3');
add_line(blk, 'wr_addr_temp_reg/1', 'wr_addr_reg/1');
add_line(blk, 'pingpang_Mux/1', 'wr_addr_reg/2');
add_line(blk, 'wr_addr_reg/1', 'wr_addr/1');

%wr_data_output
x = 4000;y= 600;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_data_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 4000 -200;y= 600;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_data_temp_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 5000;y= 650-7.5;x_width = 30;y_width = 15;
reuse_block(blk, 'wr_data', 'built-in/outport', ...
    'Position', [x y x+x_width y+y_width], 'Port', num2str(1));

add_line(blk, 'data_shift_out_concat/1', 'wr_data_temp_reg/1');
add_line(blk, 'wr_data_temp_reg/1', 'wr_data_reg/1');
add_line(blk, 'wr_data_reg/1', 'wr_data/1');
%wr_pingpang_output
x = 4000;y= 800;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_pingpang_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 4000 -200;y= 800;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_pingpang_temp_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 5000;y= 850-7.5;x_width = 30;y_width = 15;
reuse_block(blk, 'wr_pingpang', 'built-in/outport', ...
    'Position', [x y x+x_width y+y_width], 'Port', num2str(1));

add_line(blk, 'pingpang_reg/1', 'wr_pingpang_temp_reg/1');
add_line(blk, 'wr_pingpang_temp_reg/1', 'wr_pingpang_reg/1');
add_line(blk, 'wr_pingpang_reg/1', 'wr_pingpang/1');
%wr_eof_output
x = 4000;y= 1000;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_eof_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 4000 -200;y= 1000;x_width = 100;y_width = 100;
reuse_block(blk, 'wr_eof_temp_reg', 'xbsIndex_r4/Register', ...
    'Position', [x y x+x_width y+y_width]...  
    ); 

x = 5000;y= 1050-7.5;x_width = 30;y_width = 15;
reuse_block(blk, 'wr_eof', 'built-in/outport', ...
    'Position', [x y x+x_width y+y_width], 'Port', num2str(1));

add_line(blk, 'concat_data_carry_cnt2/2', 'wr_eof_temp_reg/1');
add_line(blk, 'wr_eof_temp_reg/1', 'wr_eof_reg/1');
add_line(blk, 'wr_eof_reg/1', 'wr_eof/1');


clean_blocks(blk);
save_state(blk, 'defaults', defaults, varargin{:});
clog('exiting pfb_fir_real_init','trace');
